export const COUNTRIES_DICTIONARY = [
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Belarus',
  'Belgium',
  'Brazil',
  'Canada',
  'China',
  'Cyprus',
  'Czechia',
  'Egypt',
  'Estonia',
  'France',
  'Georgia',
  'Germany',
  'Hungary',
  'India',
  'Israel',
  'Italy',
  'Japan',
  'Kazakhstan',
  'Kyrgyzstan',
  'Latvia',
  'Lithuania',
  'Moldova',
  'Montenegro',
  'Netherlands',
  'Poland',
  'Portugal',
  'Russia',
  'Serbia',
  'Spain',
  'Sweden',
  'Switzerland',
  'Tajikistan',
  'Thailand',
  'Turkey',
  'UAE',
  'Ukraine',
  'United Kingdom',
  'USA',
  'Uzbekistan'
] as const;

export type CountryName = typeof COUNTRIES_DICTIONARY[number];